# Main configuration for FreeBSD Core Elections

title = 2026 FreeBSD Core Team Election
descr = 2026 FreeBSD core team election

<Model::FBCE>
  <connect_info>
    dsn = "dbi:Pg:dbname=fbce"
    user = "fbce"
    password = "replaceme"
  </connect_info>
</Model::FBCE>

<Model::Schedule>
  nominating_starts = 2026-04-22 18:00:00 UTC
  nominating_ends = 2026-04-29 18:00:00 UTC
  voting_starts = 2026-04-29 18:00:00 UTC
  voting_ends = 2026-05-27 18:00:00 UTC
  announcement = 2026-06-03 18:00:00 UTC
  investiture = 2026-06-10 18:00:00 UTC
</Model::Schedule>

<Model::Rules>
  max_votes = 9
  cutoff = 1 year
</Model::Rules>

<Plugin::Session>
  expires = 7200
  cookie_expires = 0
  cookie_secure = 1
  storage = /tmp/fbce.__UID__/session-cache
  unlink_on_exit = 0
  cache_size = 8m
</Plugin::Session>
