#!/bin/sh
#
# These are instructions for creating and populating the FBCE
# database.  Note that although this is a syntactically correct shell
# script, it will not (or at least should not) run unmodified.
#

# Initialize PostgreSQL
sudo service postgresql initdb
sudo service postgresql start

# Create a superuser for myself
sudo -u postgres createuser -s des

# Create a regular user and database for FBCE
createuser -S -D -R fbce
createdb -E utf8 -O fbce fbce

# Create the schema
psql -f db/fbce.sql fbce fbce

# Regenerate the DBIC schema
#
# Note that this will not overwrite lib/FBCE/Model/FBCE.pm, but
# instead create lib/FBCE/Model/FBCE.pm.new.  You may replace the old
# file with the new, but you should remove the connect_info and place
# it in fbce_local.conf instead (copy the <Model::FBCE> section from
# fbce.conf and insert the correct host, user and password).
#
./db/update.sh fbce

# One-liner to set a user's password
perl -Ilib -MFBCE -e 'FBCE->model("FBCE::Person")->find({ login => "kenneth36" })->set_password("4ltInn!?")'

# One-liner to reset everybody's passwords
perl -Ilib -MFBCE -e 'map { $_->reset_password() } FBCE->model("FBCE::Person")->all();'

#
# The list of users is generated on freefall using scripts written for
# that purpose by gjb:
#
# % ./genuserlist.sh
# % sort users.txt >users-20260221.txt
#
./script/fbce_user.pl import users-20260221.txt

#
# Now we just need to get everybody's name:
#
# % getent passwd >gecos-20260221.txt
# 
# The script will ignore entries for which there is no user in the
# database.
#
./script/fbce_user.pl gecos gecos-20260221.txt

#
# The smash command clears the active and incumbent flags for all
# users:
#
./script/fbce_user.pl smash

#
# The list of active committers is extracted from git:
#
for repo in src ports doc ; do \
    TZ=UTC git -C ~/freebsd/$repo/main log --first-parent \
     --pretty=%cL --since '2024-04-29 18:00:00' ; \
done | uniq | sort -u >active-20260429.txt

#
# Activate everyone on that list.  Note that it is normal to get “No
# such user” errors for people who have committed in the past two
# years but have since left the project.
#
./script/fbce_user.pl activate active-20180516.txt

#
# The list of incumbents is obtained from freefall:
#
# % getent group core | cut -d: -f4 | tr , '\n' >core-20260429.txt
#
./script/fbce_user.pl incumbent core-20260221.txt

#
# Finally, generate a random password for every user who doesn't
# already have one, and create a tarball containing all the generated
# password:
#
./script/fbce_user.pl pwgen

#
# The resulting fbce-passwords.tgz can now be sent to clusteradm who
# will untar it in /home on freefall.
#

# Print the logins of active users who haven't voted
perl -Ilib -MFBCE -e 'map { print $_->login, "\n" } grep { $_->active && $_->votes_voters->count == 0 } FBCE->model("FBCE::Person")->all'
